### ISSUE TITLE
No module named 'pandas'

### ISSUE THREAD

**Issue by Trade2Million** [CryptoRobotFr/Backtest-Tools-V2#1]
Salut j'ai une erreur a l'execution du 1er block multi_envelope.ipynb : 

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[10], [line 3](vscode-notebook-cell:?execution_count=10&line=3)
      [1](vscode-notebook-cell:?execution_count=10&line=1) import sys
      [2](vscode-notebook-cell:?execution_count=10&line=2) sys.path.append('../..')
----> [3](vscode-notebook-cell:?execution_count=10&line=3) import pandas as pd
      [4](vscode-notebook-cell:?execution_count=10&line=4) pd.options.mode.chained_assignment = None  # default='warn'
      [5](vscode-notebook-cell:?execution_count=10&line=5) import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'pandas'

Pourtant pandas est bien installé : Requirement already satisfied: pandas in c:\users\....

Merci.

**Comment by Trade2Million** [comment]
Je rajoute la liste des problèmes en image
![image](https://github.com/user-attachments/assets/90008871-ee8d-4c09-b8b2-742bbb310e5b)

**Comment by 0verTube** [comment]
c est simple tu ouvre un cmd dans le ficher
![image](https://github.com/user-attachments/assets/a0a9581c-d84e-4adc-a583-542053216116)
puis tu rentre sa dans le cmd ".venv\Scripts\activate"

puis ensuite tu peut simplement installer avec la commande "pip install pandas"

et pour tous les autre qui ne marcherons pas

**Comment by Trade2Million** [comment]
Salut, merci mais toujours le même problème vu qu'il me dit que pandas est déjà installé :/
![image](https://github.com/user-attachments/assets/c2db7d7d-1cf0-4ad9-a217-6d1a8920bd7d)
